defaults: &defaults
  docker:
  - image: circleci/python:3

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
    - checkout
    - persist_to_workspace:
        root: .
        paths:
          - "*"

  build:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /tmp/src
    - setup_remote_docker
    - run:
        name: Fetch manylinux docker image
        command: |
          docker pull quay.io/pypa/manylinux1_x86_64
          docker tag quay.io/pypa/manylinux1_x86_64 manylinux
    - run:
        name: Build the wheels
        command: docker run --rm -v /tmp/src:/src manylinux /src/.circleci/build
    - persist_to_workspace:
        root: .
        paths:
          - wheelhouse

  upload:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /tmp/workspace


workflows:
  version: 2

  devel:
    jobs:
    - checkout
    - build:
        requires:
          - checkout

  release:
    jobs:
    - checkout:
        filters:
          tags:
            only: /^.*/
          branches:
            ignore: /.*/
    - build:
        filters:
          tags:
            only: /^.*/
          branches:
            ignore: /.*/
        requires:
          - checkout

    - upload:
        filters:
          tags:
            only: /^.*/
          branches:
            only: /^v.*/
        requires:
          - build


