defaults: &defaults
  docker:
  - image: circleci/python:3

version: 2
jobs:
  build:
    machine:
      image: circleci/python:3
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Fetch manylinux docker image
        command: |
          docker pull quay.io/pypa/manylinux1_x86_64
          docker tag quay.io/pypa/manylinux1_x86_64 manylinux
    - run:
        name: Build the wheels
        command: docker run --rm -v $(pwd):/src manylinux /src/.circleci/build
    - persist_to_workspace:
        root: wheelhouse
        paths:
          - "*"
  upload:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /tmp/workspace


workflows:
  version: 2

  devel:
    jobs:
    - build

  release:
    jobs:
    - build:
        context: org-global
        filters:
          tags:
            only: /^.*/
          branches:
            ignore: /.*/

    - upload:
        context: org-global
        filters:
          tags:
            only: /^.*/
          branches:
            only: /^v.*/
        requires:
          - build


