defaults: &defaults
  docker:
  - image: circleci/python:3

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
    - checkout
    - persist_to_workspace:
        root: .
        paths:
          - "*"

  build:
    docker:
    - image: quay.io/pypa/manylinux1_x86_64
    steps:
    - attach_workspace:
        at: /tmp/src
    - run:
        name: Build source release
        command: |
          cd /tmp/src
          PYTHON=$(ls /opt/python/*/bin/python | head -1)
          $PYTHON setup.py sdist
    - run:
        name: Build the wheels
        command: |
          cd /tmp/src
          for PYBIN in /opt/python/*/bin; do
            "${PYBIN}/pip" wheel . -w wheelhouse/
          done
    - run:
        name: Audit and relabel the wheels
        command: |
          cd /tmp/src
          for whl in wheelhouse/*.whl; do
            auditwheel repair "$whl" -w wheelhouse/
          done
    - persist_to_workspace:
        root: /tmp/src
        paths:
          - wheelhouse/*manylinux*
          - dist/*.tar.gz

  upload:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Install twine
        command: sudo pip install twine
    - run:
        name: Upload to PyPI
        command: 
          twine upload -u $PYPI_USER -p "$PYPI_PASSWORD" /tmp/workspace/wheelhouse/*.whl /tmp/workspace/dist/*.tar.gz



workflows:
  version: 2

  devel:
    jobs:
    - checkout
    - build:
        requires:
          - checkout

  release:
    jobs:
    - checkout:
        filters:
          tags:
            only: /^.*/
          branches:
            ignore: /.*/
    - build:
        filters:
          tags:
            only: /^.*/
          branches:
            ignore: /.*/
        requires:
          - checkout

    - upload:
        context: pypi
        filters:
          tags:
            only: /^.*/
          branches:
            only: /^v.*/
        requires:
          - build


